"use client";

import { useMemo, useState } from "react";
import { Activity, AlertTriangle, CheckCircle2, Database, Download, Eye, FileCheck2, HardDriveDownload, RefreshCw, Search, ShieldAlert, SlidersHorizontal, UserX, Users } from "lucide-react";
import { systemServices } from "@/lib/mock-data";
import { formatKES } from "@/lib/utils";
import { Badge, Card, Modal, Toggle } from "@/components/ui/core";
import { MetricCard, MiniLineChart, ProgressBar } from "@/components/ui/metrics";
import { Section } from "@/components/shared/section";
import { Status } from "@/components/shared/status";

const users = [
  { id: "USR-10091", name: "Peter Otieno", phone: "+254 712 345 678", role: "Consumer", kyc: "VERIFIED", status: "ACTIVE", wallet: 12840 },
  { id: "USR-10088", name: "Wakulima Fresh Ltd", phone: "+254 722 991 400", role: "Retailer", kyc: "VERIFIED", status: "ACTIVE", wallet: 86420 },
  { id: "USR-10079", name: "Eastern Grain Co.", phone: "+254 733 283 101", role: "Wholesaler", kyc: "VERIFIED", status: "ACTIVE", wallet: 242800 },
  { id: "USR-10072", name: "David Mwangi", phone: "+254 701 552 144", role: "Rider", kyc: "VERIFIED", status: "ACTIVE", wallet: 9460 },
  { id: "USR-10069", name: "Amina Yusuf", phone: "+254 741 992 302", role: "Retailer", kyc: "PENDING", status: "PENDING_KYC_REVIEW", wallet: 0 }
];

const kycItems = [
  { id: "KYC-922", name: "Amina Yusuf", role: "Retailer", doc: "Business Certificate", age: "42 min", extracted: "Business name • PIN", risk: "Low" },
  { id: "KYC-919", name: "John Kibet", role: "Rider", doc: "Driving Licence", age: "2 hr", extracted: "Name • licence no.", risk: "Low" },
  { id: "KYC-915", name: "Lake Foods Ltd", role: "Wholesaler", doc: "Tax PIN + Certificate", age: "5 hr", extracted: "Company • tax PIN", risk: "Review" }
];

const disputes = [
  { id: "DSP-203", order: "MP-ORD-1028", consumer: "C. Wanjiku", vendor: "Fresh Basket", reason: "Wrong Items", amount: 870, status: "OPEN", evidence: 2 },
  { id: "DSP-197", order: "MP-ORD-1014", consumer: "J. Naliaka", vendor: "City Greens", reason: "Damaged Items", amount: 1250, status: "REVIEWING", evidence: 3 },
  { id: "DSP-191", order: "MP-ORD-997", consumer: "M. Abdi", vendor: "Coast Foods", reason: "Not Delivered", amount: 3140, status: "RESOLVED", evidence: 1 }
];

const fraud = [
  { id: "FR-882", user: "USR-10012", signal: "Velocity anomaly", amount: 69000, risk: 92, state: "BLOCKED" },
  { id: "FR-879", user: "USR-10051", signal: "New device + unusual amount", amount: 42000, risk: 86, state: "REVIEW" },
  { id: "FR-874", user: "USR-10077", signal: "Repeated failed transfers", amount: 17500, risk: 74, state: "REVIEW" }
];

const audit = [
  { time: "17:31:08", actor: "admin@marketpay", action: "KYC_APPROVED", target: "USR-10067", result: "SUCCESS" },
  { time: "17:24:42", actor: "admin@marketpay", action: "CONFIG_UPDATED", target: "daily_transaction_limit", result: "SUCCESS" },
  { time: "17:19:16", actor: "risk.ops", action: "FRAUD_FALSE_POSITIVE", target: "FR-867", result: "SUCCESS" },
  { time: "16:58:10", actor: "data.ops", action: "PRICE_RECORD_QUARANTINED", target: "OBS-551872", result: "SUCCESS" }
];

export function AdminWorkspace({ section }: { section: string }) {
  if (section === "users") return <UsersPage />;
  if (section === "kyc") return <KycPage />;
  if (section === "disputes") return <DisputesPage />;
  if (section === "fraud") return <FraudPage />;
  if (section === "data-pipeline") return <DataPipelinePage />;
  if (section === "monitoring") return <MonitoringPage />;
  if (section === "backups") return <BackupsPage />;
  if (section === "config") return <ConfigPage />;
  if (section === "audit") return <AuditPage />;
  return <Overview />;
}

function Overview() {
  return <div className="space-y-5">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Active users" value="48,216" detail="+1,284 this month" icon={<Users className="h-5 w-5"/>}/><MetricCard label="Pending KYC" value="23" detail="7 older than 12 hours" icon={<FileCheck2 className="h-5 w-5"/>}/><MetricCard label="Open disputes" value="8" detail="KES 26.4k in frozen escrow" icon={<AlertTriangle className="h-5 w-5"/>}/><MetricCard label="Active risk flags" value="4" detail="1 high severity" icon={<ShieldAlert className="h-5 w-5"/>}/></div>
    <div className="grid gap-5 xl:grid-cols-[1.3fr_.9fr]">
      <Section title="Platform health" description="Operational summary across MarketPay services."><ServiceTable compact/></Section>
      <Section title="Risk & operations queue" description="Items needing administrator review."><div className="space-y-3"><QueueItem title="Critical fraud investigation" detail="FR-882 • KES 69,000 velocity anomaly" tone="danger"/><QueueItem title="KYC awaiting review" detail="23 submissions • oldest 14h 22m" tone="warning"/><QueueItem title="Delivery service degraded" detail="p95 latency 486ms • 4.9% errors" tone="warning"/><QueueItem title="Data quality quarantine" detail="17 price records require validation" tone="info"/></div></Section>
    </div>
    <Section title="Recent administrative activity" description="Every privileged action is auditable."><AuditTable /></Section>
  </div>;
}

function UsersPage() {
  const [query,setQuery]=useState(""); const [selected,setSelected]=useState<(typeof users)[number]|null>(null); const [suspended,setSuspended]=useState<string[]>([]);
  const filtered=useMemo(()=>users.filter(u=>`${u.name} ${u.phone} ${u.role} ${u.kyc}`.toLowerCase().includes(query.toLowerCase())),[query]);
  return <div className="space-y-5"><Card className="p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input className="mp-input pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search phone, name, role or KYC status"/></label><button className="mp-btn-secondary"><Download className="h-4 w-4"/> Export non-PII CSV</button></div></Card><Section title="User accounts" description="Search and manage platform accounts. Suspension invalidates sessions in the backend integration contract."><div className="overflow-x-auto"><table className="mp-table"><thead><tr><th>User</th><th>Phone</th><th>Role</th><th>KYC</th><th>Status</th><th>Wallet</th><th></th></tr></thead><tbody>{filtered.map(u=><tr key={u.id}><td><p className="font-semibold">{u.name}</p><p className="text-xs text-slate-400">{u.id}</p></td><td>{u.phone}</td><td>{u.role}</td><td><Status value={u.kyc}/></td><td><Status value={suspended.includes(u.id)?"SUSPENDED":u.status}/></td><td>{formatKES(u.wallet)}</td><td><button onClick={()=>setSelected(u)} className="mp-btn-secondary !px-3 !py-2"><Eye className="h-4 w-4"/> View</button></td></tr>)}</tbody></table></div></Section><Modal open={!!selected} onClose={()=>setSelected(null)} title={selected?.name??"User"} description={selected ? `${selected.id} • ${selected.role}` : ""} width="max-w-2xl" footer={selected&&<><button className="mp-btn-secondary" onClick={()=>setSelected(null)}>Close</button><button className="mp-btn-danger" onClick={()=>{setSuspended(v=>[...new Set([...v,selected.id])]);setSelected(null)}}><UserX className="h-4 w-4"/> Suspend account</button></>} >{selected&&<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Card className="p-3"><p className="text-xs text-slate-500">Wallet balance</p><p className="mt-1 font-extrabold">{formatKES(selected.wallet)}</p></Card><Card className="p-3"><p className="text-xs text-slate-500">KYC status</p><p className="mt-1 font-extrabold">{selected.kyc}</p></Card><Card className="p-3"><p className="text-xs text-slate-500">Orders</p><p className="mt-1 font-extrabold">18</p></Card></div><div className="rounded-xl border border-slate-200 p-4"><p className="font-semibold">Account activity</p><div className="mt-3 grid gap-2 text-sm text-slate-600"><p>Last sign-in: Today, 16:42</p><p>Transactions this month: 27</p><p>Open orders: 1</p><p>Audit events: 43</p></div></div></div>}</Modal></div>;
}

function KycPage(){const[review,setReview]=useState<(typeof kycItems)[number]|null>(null);const[resolved,setResolved]=useState<string[]>([]);return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><MetricCard label="Pending review" value={String(kycItems.length-resolved.length)} detail="24–48 hour SLA" icon={<FileCheck2 className="h-5 w-5"/>}/><MetricCard label="Approved today" value="31" detail="Median review 2.4h" icon={<CheckCircle2 className="h-5 w-5"/>}/><MetricCard label="Needs more info" value="6" detail="Resubmission enabled" icon={<AlertTriangle className="h-5 w-5"/>}/></div><div className="grid gap-4 xl:grid-cols-3">{kycItems.filter(k=>!resolved.includes(k.id)).map(k=><Card key={k.id} className="p-4"><div className="flex items-start justify-between"><div><p className="font-extrabold">{k.name}</p><p className="text-xs text-slate-500">{k.role} • {k.id}</p></div><Badge tone={k.risk==="Low"?"success":"warning"}>{k.risk} risk</Badge></div><div className="mt-4 rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">Document</p><p className="mt-1 text-sm font-bold">{k.doc}</p><p className="mt-2 text-xs text-slate-500">OCR extracted: {k.extracted}</p></div><div className="mt-4 flex items-center justify-between"><span className="text-xs text-slate-400">Waiting {k.age}</span><button className="mp-btn-primary !px-3 !py-2" onClick={()=>setReview(k)}>Review</button></div></Card>)}</div><Modal open={!!review} onClose={()=>setReview(null)} title="KYC review" description={review ? `${review.name} • ${review.doc}`:""} width="max-w-3xl" footer={review&&<><button className="mp-btn-secondary" onClick={()=>{setResolved(v=>[...v,review.id]);setReview(null)}}>Needs more info</button><button className="mp-btn-primary" onClick={()=>{setResolved(v=>[...v,review.id]);setReview(null)}}><CheckCircle2 className="h-4 w-4"/> Approve KYC</button></>} >{review&&<div className="grid gap-4 md:grid-cols-2"><div className="grid min-h-64 place-items-center rounded-xl border-2 border-dashed border-slate-200 bg-slate-50"><div className="text-center"><FileCheck2 className="mx-auto h-10 w-10 text-brand-600"/><p className="mt-2 font-bold">Document preview</p><p className="text-xs text-slate-500">Secure image placeholder</p></div></div><div className="space-y-3"><InfoRow label="Applicant" value={review.name}/><InfoRow label="Role" value={review.role}/><InfoRow label="Document type" value={review.doc}/><InfoRow label="OCR fields" value={review.extracted}/><InfoRow label="Malware scan" value="Passed"/><InfoRow label="Identity match" value="Matched"/></div></div>}</Modal></div>}

function DisputesPage(){const[done,setDone]=useState<string[]>([]);return <Section title="Escrow dispute queue" description="Resolve consumer disputes while funds remain frozen."><div className="overflow-x-auto"><table className="mp-table"><thead><tr><th>Dispute</th><th>Order</th><th>Parties</th><th>Reason</th><th>Amount</th><th>Evidence</th><th>Status</th><th></th></tr></thead><tbody>{disputes.map(d=><tr key={d.id}><td className="font-semibold">{d.id}</td><td>{d.order}</td><td><p>{d.consumer}</p><p className="text-xs text-slate-400">vs {d.vendor}</p></td><td>{d.reason}</td><td>{formatKES(d.amount)}</td><td>{d.evidence} photo(s)</td><td><Status value={done.includes(d.id)?"RESOLVED":d.status}/></td><td>{!done.includes(d.id)&&d.status!=="RESOLVED"?<div className="flex gap-2"><button onClick={()=>setDone(v=>[...v,d.id])} className="mp-btn-primary !px-3 !py-2">Refund</button><button onClick={()=>setDone(v=>[...v,d.id])} className="mp-btn-secondary !px-3 !py-2">Release</button></div>:null}</td></tr>)}</tbody></table></div></Section>}

function FraudPage(){const[closed,setClosed]=useState<string[]>([]);return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><MetricCard label="High-risk flags" value="1" detail="Immediate review" icon={<ShieldAlert className="h-5 w-5"/>}/><MetricCard label="Wallets frozen" value="3" detail="Automated controls" icon={<AlertTriangle className="h-5 w-5"/>}/><MetricCard label="False positives" value="18" detail="Last 30 days" icon={<CheckCircle2 className="h-5 w-5"/>}/></div><Section title="Fraud investigation queue" description="Velocity, amount and device anomalies surfaced by fraud controls."><div className="space-y-3">{fraud.map(f=><Card key={f.id} className="p-4"><div className="grid items-center gap-4 lg:grid-cols-[1fr_160px_200px_260px]"><div><div className="flex items-center gap-2"><p className="font-extrabold">{f.signal}</p><Badge tone={f.risk>=90?"danger":"warning"}>Risk {f.risk}</Badge></div><p className="mt-1 text-xs text-slate-500">{f.id} • {f.user}</p></div><div><p className="text-xs text-slate-500">Amount</p><p className="font-bold">{formatKES(f.amount)}</p></div><div><ProgressBar value={f.risk}/></div><div className="flex flex-wrap justify-end gap-2">{closed.includes(f.id)?<Badge tone="success">Reviewed</Badge>:<><button onClick={()=>setClosed(v=>[...v,f.id])} className="mp-btn-secondary !px-3 !py-2">False positive</button><button onClick={()=>setClosed(v=>[...v,f.id])} className="mp-btn-danger !px-3 !py-2">Keep frozen</button></>}</div></div></Card>)}</div></Section></div>}

function DataPipelinePage(){const adapters=[{name:"Vendor Adapter",status:"ACTIVE",last:"4 min ago",records:"8,412",errors:2},{name:"Government / KNBS",status:"ACTIVE",last:"22 min ago",records:"1,230",errors:0},{name:"Weather Adapter",status:"ACTIVE",last:"13 min ago",records:"624",errors:0},{name:"Scraper Adapter",status:"DEGRADED",last:"1h 34m ago",records:"3,809",errors:18}];return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-4"><MetricCard label="Records last hour" value="14,075" detail="Across active adapters" icon={<Database className="h-5 w-5"/>}/><MetricCard label="Deduplicated" value="1,284" detail="Bloom filter" icon={<RefreshCw className="h-5 w-5"/>}/><MetricCard label="Quarantined" value="17" detail=">50% deviation" icon={<AlertTriangle className="h-5 w-5"/>}/><MetricCard label="Pipeline lag" value="18 min" detail="Within target" icon={<Activity className="h-5 w-5"/>}/></div><Section title="Ingestion adapters" description="Live operational visibility over sources feeding AI price intelligence."><div className="overflow-x-auto"><table className="mp-table"><thead><tr><th>Adapter</th><th>Status</th><th>Last successful ingestion</th><th>Records / hour</th><th>Errors</th></tr></thead><tbody>{adapters.map(a=><tr key={a.name}><td className="font-semibold">{a.name}</td><td><Status value={a.status}/></td><td>{a.last}</td><td>{a.records}</td><td className={a.errors?"font-bold text-red-600":""}>{a.errors}</td></tr>)}</tbody></table></div></Section><Section title="Validation quarantine" description="Outlier observations are withheld before AI model use."><div className="grid gap-3 md:grid-cols-3">{["Maize • Embu • KES 164/kg","Tomatoes • Kitale • KES 188/kg","Rice • Kisumu • KES 348/kg"].map((x,i)=><Card key={x} className="p-4"><Badge tone="warning">Deviation +{52+i*9}%</Badge><p className="mt-3 font-bold">{x}</p><p className="mt-1 text-xs text-slate-500">Compared with recent validated market baseline.</p><div className="mt-4 flex gap-2"><button className="mp-btn-secondary !px-3 !py-2">Reject</button><button className="mp-btn-primary !px-3 !py-2">Validate</button></div></Card>)}</div></Section></div>}

function MonitoringPage(){return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-4"><MetricCard label="Services up" value="5 / 6" detail="1 degraded" icon={<CheckCircle2 className="h-5 w-5"/>}/><MetricCard label="p95 gateway latency" value="238 ms" detail="Target <500 ms" icon={<Activity className="h-5 w-5"/>}/><MetricCard label="Platform error rate" value="1.3%" detail="5-minute window" icon={<AlertTriangle className="h-5 w-5"/>}/><MetricCard label="Active alerts" value="2" detail="1 latency • 1 ingestion" icon={<ShieldAlert className="h-5 w-5"/>}/></div><Section title="Microservice health" description="Statuses, latency and error rates aligned to the platform monitoring story."><ServiceTable/></Section><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Section title="API latency" description="Recent p95 samples in milliseconds."><div className="h-44"><MiniLineChart values={[180,192,214,205,228,260,238,246,231,239,242,238]}/></div></Section><Section title="Recent deployments" description="Last deployment outcomes."><div className="space-y-3">{[["marketplace-service","v1.18.2","SUCCESS"],["web-nextjs","v1.12.0","SUCCESS"],["logistics-service","v1.9.4","ROLLED_BACK"]].map(d=><div key={d[0]} className="flex items-center justify-between rounded-xl border border-slate-200 p-3"><div><p className="font-semibold">{d[0]}</p><p className="text-xs text-slate-500">{d[1]} • 31 Aug</p></div><Status value={d[2]}/></div>)}</div></Section></div></div>}

function BackupsPage(){const[testing,setTesting]=useState(false);const backups=[{date:"31 Aug 2026 • 02:18 UTC",type:"Daily",size:"18.4 GB",checksum:"Verified",status:"SUCCESS"},{date:"30 Aug 2026 • 02:17 UTC",type:"Daily",size:"18.1 GB",checksum:"Verified",status:"SUCCESS"},{date:"29 Aug 2026 • 02:16 UTC",type:"Daily",size:"17.9 GB",checksum:"Verified",status:"SUCCESS"},{date:"24 Aug 2026 • 02:12 UTC",type:"Weekly",size:"17.2 GB",checksum:"Verified",status:"SUCCESS"}];return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-4"><MetricCard label="Latest backup" value="02:18 UTC" detail="Completed before 03:00" icon={<HardDriveDownload className="h-5 w-5"/>}/><MetricCard label="Checksum" value="Verified" detail="Latest backup" icon={<CheckCircle2 className="h-5 w-5"/>}/><MetricCard label="Recovery target" value="< 4 hr" detail="DR validation SLA" icon={<Activity className="h-5 w-5"/>}/><MetricCard label="Retention" value="30 / 12 / 12" detail="Daily / weekly / monthly" icon={<Database className="h-5 w-5"/>}/></div><Section title="Backup verification" description="Daily, weekly and monthly backup readiness with checksum status."><div className="overflow-x-auto"><table className="mp-table"><thead><tr><th>Backup time</th><th>Type</th><th>Size</th><th>Checksum</th><th>Status</th></tr></thead><tbody>{backups.map(b=><tr key={b.date}><td className="font-semibold">{b.date}</td><td>{b.type}</td><td>{b.size}</td><td><Badge tone="success">{b.checksum}</Badge></td><td><Status value={b.status}/></td></tr>)}</tbody></table></div></Section><Section title="Disaster recovery test" description="UI control for a controlled test restore into a non-production environment."><div className="grid gap-4 md:grid-cols-[1fr_auto] md:items-center"><div><p className="font-bold text-slate-900">Restore latest verified backup</p><p className="mt-1 text-sm text-slate-500">Production integration must require privileged authorization, isolate the test environment and record the test outcome.</p>{testing&&<div className="mt-3 rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-700"><RefreshCw className="mr-2 inline h-4 w-4 animate-spin"/>DR test preview started. No real infrastructure action is performed by this UI-only build.</div>}</div><button onClick={()=>setTesting(true)} className="mp-btn-primary"><HardDriveDownload className="h-4 w-4"/> Start DR test</button></div></Section></div>}

function ConfigPage(){const[push,setPush]=useState(true);const[saved,setSaved]=useState(false);return <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Section title="Platform configuration" description="Update operational parameters without a code deployment. This UI is ready for a configuration API."><div className="grid gap-4 sm:grid-cols-2"><label><span className="mp-label">Daily transaction limit (KES)</span><input className="mp-input" defaultValue="70000"/></label><label><span className="mp-label">Delivery fee per km (KES)</span><input className="mp-input" defaultValue="35"/></label><label><span className="mp-label">Price alert threshold (%)</span><input className="mp-input" defaultValue="10"/></label><label><span className="mp-label">Auto-cancel timeout (minutes)</span><input className="mp-input" defaultValue="20"/></label><label className="sm:col-span-2"><span className="mp-label">Accepted KYC document types</span><input className="mp-input" defaultValue="National ID, Business Certificate, Tax PIN, Driving Licence"/></label></div><div className="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-xl bg-slate-50 p-4"><Toggle checked={push} onChange={setPush} label="Enable operational push notifications"/><button onClick={()=>setSaved(true)} className="mp-btn-primary"><SlidersHorizontal className="h-4 w-4"/> Save configuration</button></div>{saved&&<div className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">Configuration saved in UI demo state. Production integration should submit old/new values and administrator identity for the audit log.</div>}</Section><Section title="Change controls" description="Guardrails represented in the interface."><div className="space-y-3"><InfoRow label="Propagation target" value="Within 60 seconds"/><InfoRow label="Audit logging" value="Required"/><InfoRow label="Rollback" value="Previous value retained"/><InfoRow label="Promotion fee" value="Zero allowed"/></div><div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Production configuration writes should be permission-gated and confirmed server-side. This frontend does not implement privileged backend changes.</div></Section></div>}

function AuditPage(){return <div className="space-y-5"><Card className="p-4"><div className="grid gap-3 md:grid-cols-[1fr_180px_180px]"><label className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input className="mp-input pl-9" placeholder="Search actor, action or target"/></label><input type="date" className="mp-input" defaultValue="2026-08-31"/><button className="mp-btn-secondary"><Download className="h-4 w-4"/> Export audit CSV</button></div></Card><Section title="Administrative audit log" description="Immutable-style activity view for privileged platform actions."><AuditTable/></Section></div>}

function ServiceTable({compact=false}:{compact?:boolean}){const rows=compact?systemServices.slice(0,4):systemServices;return <div className="overflow-x-auto"><table className="mp-table"><thead><tr><th>Service</th><th>Status</th><th>p95 latency</th><th>Error rate</th></tr></thead><tbody>{rows.map(s=><tr key={s.name}><td className="font-semibold">{s.name}</td><td><Status value={s.status}/></td><td className={s.latency>400?"font-bold text-amber-600":""}>{s.latency} ms</td><td>{s.error}%</td></tr>)}</tbody></table></div>}
function AuditTable(){return <div className="overflow-x-auto"><table className="mp-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th><th>Result</th></tr></thead><tbody>{audit.map((a,i)=><tr key={`${a.time}-${i}`}><td className="font-mono text-xs">{a.time}</td><td>{a.actor}</td><td className="font-semibold">{a.action}</td><td className="font-mono text-xs">{a.target}</td><td><Status value={a.result}/></td></tr>)}</tbody></table></div>}
function QueueItem({title,detail,tone}:{title:string;detail:string;tone:"danger"|"warning"|"info"}){return <div className="flex items-start gap-3 rounded-xl border border-slate-200 p-3"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${tone==="danger"?"bg-red-500":tone==="warning"?"bg-amber-500":"bg-blue-500"}`}/><div><p className="text-sm font-bold text-slate-900">{title}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div></div>}
function InfoRow({label,value}:{label:string;value:string}){return <div className="flex items-start justify-between gap-3 rounded-xl border border-slate-200 px-3 py-2.5"><span className="text-xs text-slate-500">{label}</span><span className="text-right text-sm font-semibold text-slate-800">{value}</span></div>}
