"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, CheckCircle2, FileUp, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { AuthShell } from "@/components/auth/auth-shell";

const steps = ["Phone", "OTP", "Profile", "Security", "KYC"];
export default function RegisterPage(){const router=useRouter();const[step,setStep]=useState(0);const[role,setRole]=useState("Consumer");const next=()=>step<steps.length-1?setStep(s=>s+1):router.push(role==="Rider"?"/rider":role==="Retailer"?"/vendor":role==="Wholesaler"?"/wholesaler":"/consumer");return <AuthShell eyebrow="Account registration" title="Join MarketPay" description="A guided UI for phone verification, profile setup, password security and role-specific KYC.">
  <div className="mb-6 flex items-center gap-2">{steps.map((s,i)=><div key={s} className="flex min-w-0 flex-1 items-center gap-2"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full text-xs font-bold ${i<=step?"bg-brand-600 text-white":"bg-slate-100 text-slate-400"}`}>{i<step?<CheckCircle2 className="h-4 w-4"/>:i+1}</span><span className="hidden truncate text-[10px] font-bold uppercase text-slate-500 sm:block">{s}</span></div>)}</div>
  {step===0&&<div className="space-y-4"><label><span className="mp-label">I am registering as</span><select className="mp-input" value={role} onChange={e=>setRole(e.target.value)}><option>Consumer</option><option>Retailer</option><option>Wholesaler</option><option>Rider</option></select></label><label><span className="mp-label">Mobile number</span><input className="mp-input" placeholder="+254 7XX XXX XXX" defaultValue="+254 "/></label><div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-700">A 6-digit verification code will be sent to this E.164 phone number.</div></div>}
  {step===1&&<div className="space-y-4"><p className="text-sm text-slate-600">Enter the 6-digit code sent to <strong>+254 712 345 678</strong>. It expires in 5 minutes.</p><div className="grid grid-cols-6 gap-2">{Array.from({length:6},(_,i)=><input key={i} className="h-12 min-w-0 rounded-xl border border-slate-200 text-center text-lg font-bold outline-none focus:border-brand-400" maxLength={1} defaultValue={i<4?String(i+2):""}/>)}</div><button className="text-sm font-bold text-brand-700">Resend OTP</button></div>}
  {step===2&&<div className="grid gap-4 sm:grid-cols-2"><label><span className="mp-label">Full name</span><input className="mp-input" placeholder="Your full name"/></label><label><span className="mp-label">Email</span><input type="email" className="mp-input" placeholder="you@example.com"/></label><label className="sm:col-span-2"><span className="mp-label">Location</span><input className="mp-input" placeholder="Town / market / county"/></label></div>}
  {step===3&&<div className="space-y-4"><label><span className="mp-label">Password</span><input type="password" className="mp-input" defaultValue="MarketPay#2026"/></label><label><span className="mp-label">Confirm password</span><input type="password" className="mp-input" defaultValue="MarketPay#2026"/></label><div className="grid grid-cols-2 gap-2 text-xs">{["8+ characters","1 uppercase","1 digit","1 symbol"].map(x=><div key={x} className="flex items-center gap-2 rounded-lg bg-emerald-50 p-2 text-emerald-700"><CheckCircle2 className="h-3.5 w-3.5"/>{x}</div>)}</div></div>}
  {step===4&&<div className="space-y-4">{role==="Consumer"?<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><ShieldCheck className="h-5 w-5 text-emerald-700"/><p className="mt-2 font-bold text-emerald-900">Consumer registration is ready</p><p className="mt-1 text-xs text-emerald-700">Your wallet will be provisioned automatically when backend registration succeeds.</p></div>:<><p className="text-sm text-slate-600">{role} accounts require identity or business verification before elevated marketplace access.</p><label className="grid min-h-36 cursor-pointer place-items-center rounded-xl border-2 border-dashed border-slate-200 bg-slate-50 text-center"><span><FileUp className="mx-auto h-7 w-7 text-brand-600"/><strong className="mt-2 block text-sm">Upload KYC document</strong><span className="text-xs text-slate-500">National ID, Business Certificate, Tax PIN or Driving Licence</span></span><input type="file" className="hidden"/></label></>}</div>}
  <div className="mt-6 flex items-center justify-between gap-3"><button onClick={()=>step===0?router.push("/login"):setStep(s=>s-1)} className="mp-btn-secondary"><ArrowLeft className="h-4 w-4"/>{step===0?"Back to login":"Back"}</button><button onClick={next} className="mp-btn-primary">{step===steps.length-1?"Complete registration":"Continue"}<ArrowRight className="h-4 w-4"/></button></div>
  <p className="mt-5 text-center text-xs text-slate-400">By continuing you agree to the MarketPay terms and privacy policy.</p>
</AuthShell>}
